### ISSUE TITLE
UC Irvine links are broken

### ISSUE THREAD

**Issue by sxotney** [shanirivers/open-source-mathematics-degree#2]
I checked a couple of UC Irvine courses linked through here and they seem to be missing a slash in the url as per below: 

https://open.uci.educourses/math_1a1b_precalculus.html 

should be:
https://open.uci.edu/courses/math_1a1b_precalculus.html

**Comment by shanirivers** [comment]
Thank you. I will update it now.

**Comment by shanirivers** [comment]
Update made to link.
